### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#790]
```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/avni-webapp/issues/1300
- [ ] https://github.com/avniproject/avni-server/issues/785
- [ ] https://github.com/avniproject/avni-server/issues/784
- [ ] https://github.com/avniproject/avni-client/issues/1467
- [ ] https://github.com/avniproject/avni-webapp/issues/1317
- [ ] https://github.com/avniproject/avni-media/issues/179
```
