### ISSUE TITLE
Release 10.0.1 server and webapp

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#807]
### AC:
- Release 10.0.1 server and webapp
- No need to send mail

### Post deployment tasks(by developer)
- Merging, tagging
- Release notes

### Analysis notes:(Cards involved)

```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/avni-server/issues/798
- [ ] https://github.com/avniproject/avni-webapp/issues/1354
- [ ] https://github.com/avniproject/avni-webapp/issues/1355
- [ ] https://github.com/avniproject/avni-webapp/issues/1350
- [ ] https://github.com/avniproject/avni-server/issues/794
```
